site_name: MinerU使用文档





# Navigation -------------------------------------
nav:
  - '首页': 'index.md'
  - '关于MinerU':
    - '产品简介': 'about/introduction.md'
    - '主要功能': 'about/features.md'
    - '产品矩阵': 'about/matrix.md'
  - '版本更新说明':
    - 'Web/客户端': 'release-notes/web-client.md'
    - '开源版本': 'release-notes/open-source.md'
    - '在线API服务': 'release-notes/api-service.md'
  - '快速开始':
    - '本地部署': 'quick-start/local-deployment.md'
    - 'Web/客户端': 'quick-start/web-client.md'
    - '在线API服务': 'quick-start/api-service.md'
    - '插件与生态': 'quick-start/plugins.md'
  - '使用指南':
    - '本地部署': 'user-guides/local-deployment.md'
    - 'Web/客户端': 'user-guides/web-client.md'
    - '在线API服务': 'user-guides/api-service.md'
    - '插件与生态': 'user-guides/plugins.md'
  - '常见问题': 'faq.md'
  - '联系我们': 'contact.md'
  - '友情链接': 'links.md'